"""Type stubs for Supabase library to improve type checking."""

from typing import Any

class SupabaseQueryResult:
    """Result from Supabase query."""

    data: list[dict[str, Any]] | None
    error: dict[str, Any] | None
    count: int | None

class SupabaseTable:
    """Supabase table operations."""

    def select(self, columns: str = "*") -> "SupabaseQueryBuilder": ...
    def insert(self, data: dict[str, Any] | list[dict[str, Any]]) -> "SupabaseQueryBuilder": ...
    def update(self, data: dict[str, Any]) -> "SupabaseQueryBuilder": ...
    def delete(self) -> "SupabaseQueryBuilder": ...
    def upsert(self, data: dict[str, Any] | list[dict[str, Any]]) -> "SupabaseQueryBuilder": ...

class SupabaseQueryBuilder:
    """Supabase query builder for chaining operations."""

    def eq(self, column: str, value: Any) -> "SupabaseQueryBuilder": ...
    def neq(self, column: str, value: Any) -> "SupabaseQueryBuilder": ...
    def gt(self, column: str, value: Any) -> "SupabaseQueryBuilder": ...
    def lt(self, column: str, value: Any) -> "SupabaseQueryBuilder": ...
    def in_(self, column: str, values: list[Any]) -> "SupabaseQueryBuilder": ...
    def ilike(self, column: str, pattern: str) -> "SupabaseQueryBuilder": ...
    def or_(self, filters: str) -> "SupabaseQueryBuilder": ...
    def limit(self, count: int) -> "SupabaseQueryBuilder": ...
    def order(self, column: str, desc: bool = False) -> "SupabaseQueryBuilder": ...
    def execute(self) -> SupabaseQueryResult: ...

class SupabaseClient:
    """Main Supabase client."""

    def table(self, table_name: str) -> SupabaseTable: ...
    def from_(self, table_name: str) -> SupabaseTable: ...
    def rpc(self, function_name: str, params: dict[str, Any] | None = None) -> SupabaseQueryBuilder: ...

Client = SupabaseClient  # Type alias for backward compatibility

def create_client(url: str, key: str) -> SupabaseClient: ...
