from .async_configs import BrowserConfig
from .async_logger import AsyncLoggerBase
from _typeshed import Incomplete
from typing import Any

class BrowserProfiler:
    console: Incomplete
    logger: Incomplete
    profiles_dir: Incomplete
    builtin_browser_dir: Incomplete
    builtin_config_file: Incomplete
    def __init__(self, logger: AsyncLoggerBase | None = None) -> None: ...
    async def create_profile(self, profile_name: str | None = None, browser_config: BrowserConfig | None = None) -> str | None: ...
    def list_profiles(self) -> list[dict[str, Any]]: ...
    def get_profile_path(self, profile_name: str) -> str | None: ...
    def delete_profile(self, profile_name_or_path: str) -> bool: ...
    async def interactive_manager(self, crawl_callback=None) -> None: ...
    async def launch_standalone_browser(self, browser_type: str = 'chromium', user_data_dir: str | None = None, debugging_port: int = 9222, headless: bool = False, save_as_builtin: bool = False) -> str | None: ...
    async def launch_builtin_browser(self, browser_type: str = 'chromium', debugging_port: int = 9222, headless: bool = True) -> str | None: ...
    def get_builtin_browser_info(self) -> dict[str, Any] | None: ...
    async def kill_builtin_browser(self) -> bool: ...
    async def get_builtin_browser_status(self) -> dict[str, Any]: ...
