import abc
from abc import ABC, abstractmethod
from patchright.async_api import Page as UndetectedPage
from playwright.async_api import Page
from typing import Any, Callable

Page = Any
UndetectedPage = Any

class BrowserAdapter(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    async def evaluate(self, page: Page, expression: str, arg: Any = None) -> Any: ...
    @abstractmethod
    async def setup_console_capture(self, page: Page, captured_console: list[dict]) -> Callable | None: ...
    @abstractmethod
    async def setup_error_capture(self, page: Page, captured_console: list[dict]) -> Callable | None: ...
    @abstractmethod
    async def retrieve_console_messages(self, page: Page) -> list[dict]: ...
    @abstractmethod
    async def cleanup_console_capture(self, page: Page, handle_console: Callable | None, handle_error: Callable | None): ...
    @abstractmethod
    def get_imports(self) -> tuple: ...

class PlaywrightAdapter(BrowserAdapter):
    async def evaluate(self, page: Page, expression: str, arg: Any = None) -> Any: ...
    async def setup_console_capture(self, page: Page, captured_console: list[dict]) -> Callable | None: ...
    async def setup_error_capture(self, page: Page, captured_console: list[dict]) -> Callable | None: ...
    async def retrieve_console_messages(self, page: Page) -> list[dict]: ...
    async def cleanup_console_capture(self, page: Page, handle_console: Callable | None, handle_error: Callable | None): ...
    def get_imports(self) -> tuple: ...

class StealthAdapter(BrowserAdapter):
    def __init__(self) -> None: ...
    async def apply_stealth(self, page: Page): ...
    async def evaluate(self, page: Page, expression: str, arg: Any = None) -> Any: ...
    async def setup_console_capture(self, page: Page, captured_console: list[dict]) -> Callable | None: ...
    async def setup_error_capture(self, page: Page, captured_console: list[dict]) -> Callable | None: ...
    async def retrieve_console_messages(self, page: Page) -> list[dict]: ...
    async def cleanup_console_capture(self, page: Page, handle_console: Callable | None, handle_error: Callable | None): ...
    def get_imports(self) -> tuple: ...

class UndetectedAdapter(BrowserAdapter):
    def __init__(self) -> None: ...
    async def evaluate(self, page: UndetectedPage, expression: str, arg: Any = None) -> Any: ...
    async def setup_console_capture(self, page: UndetectedPage, captured_console: list[dict]) -> Callable | None: ...
    async def setup_error_capture(self, page: UndetectedPage, captured_console: list[dict]) -> Callable | None: ...
    async def retrieve_console_messages(self, page: UndetectedPage) -> list[dict]: ...
    async def cleanup_console_capture(self, page: UndetectedPage, handle_console: Callable | None, handle_error: Callable | None): ...
    def get_imports(self) -> tuple: ...
