from _typeshed import Incomplete
from crawl4ai import BrowserConfig, BrowserProfiler, CrawlerRunConfig
from typing import Any

console: Incomplete

def get_global_config() -> dict: ...
def save_global_config(config: dict): ...
def setup_llm_config() -> tuple[str, str]: ...
async def stream_llm_response(url: str, markdown: str, query: str, provider: str, token: str): ...
def parse_key_values(ctx, param, value) -> dict[str, Any]: ...
def load_config_file(path: str | None) -> dict: ...
def load_schema_file(path: str | None) -> dict: ...
async def run_crawler(url: str, browser_cfg: BrowserConfig, crawler_cfg: CrawlerRunConfig, verbose: bool): ...
def show_examples() -> None: ...
def get_directory_size(path: str) -> int: ...
def display_profiles_table(profiles: list[dict[str, Any]]): ...
async def create_profile_interactive(profiler: BrowserProfiler): ...
def delete_profile_interactive(profiler: BrowserProfiler): ...
async def crawl_with_profile_cli(profile_path, url): ...
async def use_profile_to_crawl() -> None: ...
async def manage_profiles() -> None: ...
def cli() -> None: ...
def browser_cmd() -> None: ...
def browser_status_cmd() -> None: ...
def browser_start_cmd(browser_type: str, port: int, headless: bool): ...
def browser_stop_cmd() -> None: ...
def browser_view_cmd(url: str | None): ...
def browser_restart_cmd(browser_type: str | None, port: int | None, headless: bool | None): ...
def cdp_cmd(user_data_dir: str | None, port: int, browser_type: str, headless: bool, incognito: bool): ...
def crawl_cmd(url: str, browser_config: str, crawler_config: str, filter_config: str, extraction_config: str, json_extract: str, schema: str, browser: dict, crawler: dict, output: str, output_file: str, bypass_cache: bool, question: str, verbose: bool, profile: str, deep_crawl: str, max_pages: int): ...
def examples_cmd() -> None: ...
def config_cmd() -> None: ...
def config_list_cmd() -> None: ...
def config_get_cmd(key: str): ...
def config_set_cmd(key: str, value: str): ...
def profiles_cmd() -> None: ...
def default(url: str, example: bool, browser_config: str, crawler_config: str, filter_config: str, extraction_config: str, json_extract: str, schema: str, browser: dict, crawler: dict, output: str, bypass_cache: bool, question: str, verbose: bool, profile: str, deep_crawl: str, max_pages: int): ...
def main() -> None: ...
