from _typeshed import Incomplete

DEFAULT_PROVIDER: str
DEFAULT_PROVIDER_API_KEY: str
MODEL_REPO_BRANCH: str
PROVIDER_MODELS: Incomplete
PROVIDER_MODELS_PREFIXES: Incomplete
CHUNK_TOKEN_THRESHOLD: Incomplete
OVERLAP_RATE: float
WORD_TOKEN_RATE: float
MIN_WORD_THRESHOLD: int
IMAGE_DESCRIPTION_MIN_WORD_THRESHOLD: int
IMPORTANT_ATTRS: Incomplete
ONLY_TEXT_ELIGIBLE_TAGS: Incomplete
SOCIAL_MEDIA_DOMAINS: Incomplete
IMAGE_SCORE_THRESHOLD: int
MAX_METRICS_HISTORY: int
NEED_MIGRATION: bool
URL_LOG_SHORTEN_LENGTH: int
SHOW_DEPRECATION_WARNINGS: bool
SCREENSHOT_HEIGHT_TRESHOLD: int
PAGE_TIMEOUT: int
DOWNLOAD_PAGE_TIMEOUT: int
USER_SETTINGS: Incomplete
