from _typeshed import Incomplete

logger: Incomplete

def setup_home_directory() -> None: ...
def post_install() -> None: ...
def setup_builtin_browser() -> None: ...
def install_playwright() -> None: ...
def run_migration() -> None: ...
async def run_doctor(): ...
def doctor() -> None: ...
