from .async_configs import CrawlerRunConfig
from .async_logger import AsyncLogger
from .async_url_seeder import AsyncUrlSeeder
from .models import Links
from _typeshed import Incomplete

class LinkPreview:
    logger: Incomplete
    seeder: AsyncUrlSeeder | None
    def __init__(self, logger: AsyncLogger | None = None) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def start(self) -> None: ...
    async def close(self) -> None: ...
    async def extract_link_heads(self, links: Links, config: CrawlerRunConfig) -> Links: ...
