from _typeshed import Incomplete

logger: Incomplete

class DatabaseMigration:
    db_path: Incomplete
    content_paths: Incomplete
    def __init__(self, db_path: str) -> None: ...
    async def migrate_database(self) -> None: ...

async def backup_database(db_path: str) -> str: ...
async def run_migration(db_path: str | None = None): ...
def main() -> None: ...
