from typing import Any

class SSLCertificate(dict):
    def __init__(self, cert_info: dict[str, Any]) -> None: ...
    @staticmethod
    def from_url(url: str, timeout: int = 10) -> SSLCertificate | None: ...
    @property
    def issuer(self) -> dict[str, str]: ...
    @property
    def subject(self) -> dict[str, str]: ...
    @property
    def valid_from(self) -> str: ...
    @property
    def valid_until(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def to_json(self, filepath: str | None = None) -> str | None: ...
    def to_pem(self, filepath: str | None = None) -> str | None: ...
    def to_der(self, filepath: str | None = None) -> bytes | None: ...
