import pathlib
from ..async_configs import LLMConfig
from .c4a_result import CompilationResult, ValidationResult, WarningDetail as WarningDetail
from _typeshed import Incomplete
from lark.exceptions import VisitError as VisitError

class C4ACompiler:
    ERROR_CODES: Incomplete
    @classmethod
    def compile(cls, script: str | list[str], root: pathlib.Path | None = None) -> CompilationResult: ...
    @classmethod
    def validate(cls, script: str | list[str]) -> ValidationResult: ...
    @classmethod
    def compile_file(cls, path: str | pathlib.Path) -> CompilationResult: ...
    @staticmethod
    def generate_script(html: str, query: str | None = None, mode: str = 'c4a', llm_config: LLMConfig | None = None, **completion_kwargs) -> str: ...

def compile(script: str | list[str], root: pathlib.Path | None = None) -> CompilationResult: ...
def validate(script: str | list[str]) -> ValidationResult: ...
def compile_file(path: str | pathlib.Path) -> CompilationResult: ...
