from _typeshed import Incomplete

unifiable_n: Incomplete

def hn(tag: str) -> int: ...
def dumb_property_dict(style: str) -> dict[str, str]: ...
def dumb_css_parser(data: str) -> dict[str, dict[str, str]]: ...
def element_style(attrs: dict[str, str | None], style_def: dict[str, dict[str, str]], parent_style: dict[str, str]) -> dict[str, str]: ...
def google_list_style(style: dict[str, str]) -> str: ...
def google_has_height(style: dict[str, str]) -> bool: ...
def google_text_emphasis(style: dict[str, str]) -> list[str]: ...
def google_fixed_width_font(style: dict[str, str]) -> bool: ...
def list_numbering_start(attrs: dict[str, str | None]) -> int: ...
def skipwrap(para: str, wrap_links: bool, wrap_list_items: bool, wrap_tables: bool) -> bool: ...
def escape_md(text: str) -> str: ...
def escape_md_section(text: str, escape_backslash: bool = True, snob: bool = False, escape_dot: bool = True, escape_plus: bool = True, escape_dash: bool = True) -> str: ...
def reformat_table(lines: list[str], right_margin: int) -> list[str]: ...
def pad_tables_in_text(text: str, right_margin: int = 1) -> str: ...
