from _typeshed import Incomplete
from builtins import list as _list

logger: Incomplete
docs_manager: Incomplete

def print_table(headers: _list[str], rows: _list[_list[str]], padding: int = 2): ...
def cli() -> None: ...
def docs() -> None: ...
def combine(sections: tuple, mode: str): ...
def search(query: str, top_k: int, build_index: bool): ...
def update() -> None: ...
def index(force_facts: bool, clear_cache: bool): ...
def list() -> None: ...
