from _typeshed import Incomplete

DB_PATH: Incomplete

def init_db() -> None: ...
def alter_db_add_screenshot(new_column: str = 'media'): ...
def check_db_path() -> None: ...
def get_cached_url(url: str) -> tuple[str, str, str, str, str, str, str, bool, str] | None: ...
def cache_url(url: str, html: str, cleaned_html: str, markdown: str, extracted_content: str, success: bool, media: str = '{}', links: str = '{}', metadata: str = '{}', screenshot: str = ''): ...
def get_total_count() -> int: ...
def clear_db() -> None: ...
def flush_db() -> None: ...
def update_existing_records(new_column: str = 'media', default_value: str = '{}'): ...
