from _typeshed import Incomplete

class DocsManager:
    docs_dir: Incomplete
    local_docs: Incomplete
    logger: Incomplete
    llm_text: Incomplete
    def __init__(self, logger=None) -> None: ...
    async def ensure_docs_exist(self) -> None: ...
    async def fetch_docs(self) -> bool: ...
    def list(self) -> list[str]: ...
    def generate(self, sections, mode: str = 'extended'): ...
    def search(self, query: str, top_k: int = 5): ...
