from _typeshed import Incomplete

class VersionManager:
    home_dir: Incomplete
    version_file: Incomplete
    def __init__(self) -> None: ...
    def get_installed_version(self): ...
    def update_version(self) -> None: ...
    def needs_update(self): ...
