import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Pattern

@dataclass
class FilterStats:
    def __init__(self) -> None: ...
    @property
    def total_urls(self): ...
    @property
    def passed_urls(self): ...
    @property
    def rejected_urls(self): ...

class URLFilter(ABC, metaclass=abc.ABCMeta):
    name: Incomplete
    stats: Incomplete
    def __init__(self, name: str = None) -> None: ...
    @property
    def logger(self): ...
    @abstractmethod
    def apply(self, url: str) -> bool: ...

class FilterChain:
    filters: Incomplete
    stats: Incomplete
    def __init__(self, filters: list[URLFilter] = None) -> None: ...
    @property
    def logger(self): ...
    def add_filter(self, filter_: URLFilter) -> FilterChain: ...
    async def apply(self, url: str) -> bool: ...

class URLPatternFilter(URLFilter):
    PATTERN_TYPES: Incomplete
    patterns: Incomplete
    use_glob: Incomplete
    reverse: Incomplete
    def __init__(self, patterns: str | Pattern | list[str | Pattern], use_glob: bool = True, reverse: bool = False) -> None: ...
    def apply(self, url: str) -> bool: ...

class ContentTypeFilter(URLFilter):
    allowed_types: Incomplete
    def __init__(self, allowed_types: str | list[str], check_extension: bool = True, ext_map: dict[str, str] = ...) -> None: ...
    def apply(self, url: str) -> bool: ...

class DomainFilter(URLFilter):
    def __init__(self, allowed_domains: str | list[str] = None, blocked_domains: str | list[str] = None) -> None: ...
    def apply(self, url: str) -> bool: ...

class ContentRelevanceFilter(URLFilter):
    query_terms: Incomplete
    threshold: Incomplete
    k1: Incomplete
    b: Incomplete
    avgdl: Incomplete
    def __init__(self, query: str, threshold: float, k1: float = 1.2, b: float = 0.75, avgdl: int = 1000) -> None: ...
    async def apply(self, url: str) -> bool: ...

class SEOFilter(URLFilter):
    DEFAULT_WEIGHTS: Incomplete
    threshold: Incomplete
    def __init__(self, threshold: float = 0.65, keywords: list[str] = None, weights: dict[str, float] = None) -> None: ...
    async def apply(self, url: str) -> bool: ...
